name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: true

jobs:
  lint_and_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Run eslint
        run: yarn lint
      - name: Run typescript
        run: yarn type-check
      - name: Run typescript on end to end tests
        run: yarn type-check:e2e
      - name: Run end to end tests
        run: yarn e2e:ci
      - name: Archive end to end outputs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: end-to-end-output
          path: e2e/
